grails:
    profile: plugin
    codegen:
        defaultPackage: org.grails.plugins.config.util
    doc:
        authors: Jos Annevelink, Hans Bogaards
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
